name: phone_info
description: "A powerful Flutter plugin to fetch detailed phone hardware and network information, including device architecture (CPU, ABI), network status (IP, connection type), and other critical metrics—ideal for debugging, analytics, and dynamic feature handling."
version: 0.1.0
homepage: https://github.com/Syed-Bipul-Rahman/phone_info

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: me.bipul.phone_info.phone_info_plugin
        pluginClass: PhoneInfoPlugin
      ios:
        pluginClass: PhoneInfoPlugin
      linux:
        pluginClass: PhoneInfoPlugin
      macos:
        pluginClass: PhoneInfoPlugin
      windows:
        pluginClass: PhoneInfoPluginCApi
      web:
        pluginClass: PhoneInfoPluginWeb
        fileName: phone_info_plugin_web.dart

